-- SQL Schema for site_settings table in Supabase
-- This table is used to store dynamic configuration and contact information for the Sarvadnya Infotech website.

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Set up Row Level Security (RLS)
-- Allow anyone to read the settings (anonymous access)
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.site_settings
    FOR SELECT USING (true);

-- 3. Insert default values
-- Note: Replace these values with your actual site information if needed.
INSERT INTO public.site_settings (key, value)
VALUES 
    ('NEXT_PUBLIC_SUPPORT_PHONE', '+919876543210'),
    ('NEXT_PUBLIC_SUPPORT_EMAIL', 'info@sarvadnyainfotech.com'),
    ('NEXT_PUBLIC_OFFICE_ADDRESS', '123, Business Center, Main Road, Pune - 411001'),
    ('NEXT_PUBLIC_FACEBOOK_URL', 'https://facebook.com/sarvadnyainfotech'),
    ('NEXT_PUBLIC_INSTAGRAM_URL', 'https://instagram.com/sarvadnyainfotech'),
    ('NEXT_PUBLIC_LINKEDIN_URL', 'https://linkedin.com/company/sarvadnyainfotech'),
    ('NEXT_PUBLIC_MAP_IFRAME_URL', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.211532128!2d72.8364!3d18.9221!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTjCsDU1JzE5LjYiTiA3MsKwNTAnMTEuMCJF!5e0!3m2!1sen!2sin!4v1620000000000!5m2!1sen!2sin')
ON CONFLICT (key) DO NOTHING;

-- 4. Create an automatic update trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_site_settings_updated_at
BEFORE UPDATE ON public.site_settings
FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

-- 5. Job Applications Table
CREATE TABLE IF NOT EXISTS public.job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    job_title TEXT NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    experience TEXT NOT NULL,
    message TEXT,
    resume_url TEXT NOT NULL
);

-- Set up RLS for job_applications
ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert applications
CREATE POLICY "Allow public insert access" ON public.job_applications
    FOR INSERT WITH CHECK (true);

-- Allow authenticated users to select applications (admin)
-- For simplicity in this starter, we can allow public read if there's no auth yet, 
-- but ideally this should be restricted.
CREATE POLICY "Allow public read access for job_applications" ON public.job_applications
    FOR SELECT USING (true);

-- 6. Storage Bucket Configuration (Note: Storage is managed via API usually, but we can set up policies)
-- This assumes a bucket named 'resumes' exists or needs to be created in the dashboard.
-- To create via SQL (Supabase specific):
INSERT INTO storage.buckets (id, name, public) 
VALUES ('resumes', 'resumes', false)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for 'resumes' bucket
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'resumes');
CREATE POLICY "Admin Read" ON storage.objects FOR SELECT USING (bucket_id = 'resumes');

-- 7. Site Content Table (About, Team, etc.)
CREATE TABLE IF NOT EXISTS public.site_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section TEXT UNIQUE NOT NULL, -- 'about', 'team', etc.
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Set up RLS for site_content
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for site_content" ON public.site_content
    FOR SELECT USING (true);

CREATE POLICY "Allow admin update access for site_content" ON public.site_content
    FOR ALL USING (true); -- Ideally restricted to authenticated users

-- 8. Storage Bucket for Site Assets (Images for About, Team)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('site-assets', 'site-assets', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for 'site-assets' bucket
CREATE POLICY "Public Read" ON storage.objects FOR SELECT USING (bucket_id = 'site-assets');
CREATE POLICY "Public Upload for Assets" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'site-assets');
CREATE POLICY "Public Update for Assets" ON storage.objects FOR UPDATE USING (bucket_id = 'site-assets');
CREATE POLICY "Public Delete for Assets" ON storage.objects FOR DELETE USING (bucket_id = 'site-assets');

